---
- name: "Set nameserver config"
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  when:
    - name_servers is defined

- name: "Set MOTD"
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
  become: yes
  when:
    - motd_org is defined

- name: "Install system packages"
  package:
    name:
      - python3
      - python3-pip
      - htop
      - ncdu
      - vim
      - zip
    state: present
  become: yes
