---
- name: "Set nameserver config"
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  become: true
  when:
    - name_servers is defined

- name: "Set MOTD"
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
  become: true
  when:
    - motd_org is defined

- name: "Install default packages"
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - curl
      - gnupg
      - htop
      - ncdu
      - vim
      - zip
    update_cache: true
    state: present
  become: true
