---
default_repo_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
default_repo: "deb [arch={{ apt_arch | default('amd64') }}] {{ default_repo_url }} {{ ansible_distribution_release }} stable"
docker_version: "5:20.10.17*"
