---
default_repo_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
default_repo_arch_signed_by: "deb [arch={{ apt_arch | default('amd64') }} signed-by=/etc/apt/keyrings/docker.gpg]"
default_repo: "{{ default_repo_arch_signed_by }} {{ default_repo_url }} {{ ansible_distribution_release }} stable"
docker_version: "5:20.10.17*"
