---
default_repo: "deb [arch={{ apt_arch | default('amd64') }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
docker_version: "5:20.10.12*"
