---
- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: /tmp/docker.gpg
    mode: "0440"

# TODO: switch back to Ansible module when newer GPG keychain is supported
- name: Add Docker Apt Key
  ansible.builtin.command:
    cmd: >
      gpg
      --dearmor --true
      -o /etc/apt/keyrings/docker.gpg
      /tmp/docker.gpg
  changed_when: false
  become: true

# - name: Add Docker Apt Key
#   ansible.builtin.apt_key:
#     url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
#     keyring: /etc/apt/trusted.gpg.d/
#     state: present
#   become: true

- name: Enable Docker Apt Repo
  ansible.builtin.apt_repository:
    repo: "{{ default_repo }}"
    state: present
    update_cache: true
  become: true

# TODO: figure out why docker-ce can't be found via Ansible apt module

# - name: Install Docker CE
#   ansible.builtin.apt:
#     name: "docker-ce={{ docker_version }}"
#     state: present
#     update_cache: true
#   become: true

- name: Install Docker CE
  ansible.builtin.command:
    cmd: >
      apt install
      docker-ce={{ docker_version }}
      -y
  changed_when: false
  become: true

- name: Create docker group (for container mgmt)
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Add Ansible user to Docker group
  ansible.builtin.user:
    name: ansible
    groups: docker
    append: true
  become: true

- name: Ensure service is started
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  become: true
  notify: Test docker
