---
- name: Add Docker Apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  become: true

- name: Enable Docker Apt Repo
  ansible.builtin.apt_repository:
    repo: "{{ default_repo }}"
    state: present
    update_cache: true
  become: true

# Install set version of Docker CE so that it can be controlled
- name: Install Docker CE
  ansible.builtin.apt:
    name: "docker-ce={{ docker_version }}"
    state: present
  register: pkg_install
  become: true

- name: Create docker group (for container mgmt)
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Add Ansible user to Docker group
  ansible.builtin.user:
    name: ansible
    groups: docker
    append: true
  become: true

- name: Ensure service is started
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  become: true
  notify: Test docker
