---
- name: Create kubernetes namespace
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'namespace.yaml.j2') | from_yaml }}"
    validate:
      fail_on_error: true
    state: present

- name: Create Helm values.yaml file
  ansible.builtin.copy:
    content: "{{ chart_values | to_yaml }}"
    dest: "/tmp/{{ chart.name }}.yaml"
    mode: 0660
  when:
    - chart_values is defined

- name: Add helm repository
  kubernetes.core.helm_repository:
    name: "{{ chart.repo.name }}"
    repo_url: "{{ chart.repo.url }}"
  when:
    - chart.repo is defined

- name: Deploy helm chart to the cluster
  kubernetes.core.helm:
    name: "{{ chart.name }}"
    chart_ref: "{{ chart.path }}"
    release_namespace: "{{ namespace }}"
    update_repo_cache: true
    values_files:
      - "/tmp/{{ chart.name }}.yaml"

- name: Register a DNS record with CloudFlare
  community.general.cloudflare_dns:
    zone: "{{ chart.dnsZone }}"
    type: CNAME
    record: "{{ chart.dnsRecord }}"
    value: "{{ chart.dnsValue }}"
    account_email: "{{ cloudflare_username }}"
    account_api_token: "{{ cloudflare_api_token }}"
    state: present
  when:
    - dns_enabled | default(false) | bool
