---
- hosts: all
  vars:
    namespace: example
    deployments:
      - name: example-deployment
        app: example
        replicas: 2
        containers:
          - name: nginx
            image: nginx
            ports:
              - containerPort: 80
    services:
      - name: example-service
        app: example
        type: NodePort
        ports:
          - protocol: TCP
            port: 80
    ingress_configs:
      - name: example-ingress
        rules:
          - host: example.com
            http:
              paths:
                - path: /
                  backend:
                    serviceName: example-service
                    servicePort: 80
  roles:
    - role: marknet15.homelab.k3s_deployment
