---
- name: "Download metallb install manifests"
  get_url:
    url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/manifests/{{ file }}"
    dest: "/tmp/{{ file }}"
  with_items:
    - namespace.yaml
    - metallb.yaml
  loop_control:
    loop_var: file

- name: "Apply metallb install manifests"
  k8s:
    state: present
    src: "/tmp/{{ file }}"
  with_items:
    - namespace.yaml
    - metallb.yaml
  loop_control:
    loop_var: file

- name: "Create metallb config"
  k8s:
    state: present
    definition: "{{ lookup('template', 'metallb.yaml.j2') }}"
