---
- name: "Download helm tar gz"
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-{{ helm_version }}-linux-{{ os_arch }}.tar.gz"
    dest: "/tmp/helm-linux-{{ os_arch }}.tar.gz"

- name: "Extract helm tar gz"
  ansible.builtin.unarchive:
    src: "/tmp/helm-linux-{{ os_arch }}.tar.gz"
    dest: /tmp
    remote_src: true

- name: "Copy helm binary to /usr/local/bin"
  ansible.builtin.copy:
    src: "/tmp/linux-{{ os_arch }}/helm"
    dest: /usr/local/bin
    mode: +x
    remote_src: true
  become: true

- name: "Add stable helm chart repo"
  kubernetes.core.helm_repository:
    name: stable
    repo_url: "https://charts.helm.sh/stable"
  become: true
