---
- name: "Check k3s cluster info"
  ansible.builtin.command: kubectl cluster-info
  become: true
  ignore_errors: true
  register: k3s_check
  when:
    - k3s_main_node | default(false) | bool

- name: "Install python dependencies"
  ansible.builtin.pip:
    name:
      - pyyaml
      - kubernetes
      - kubernetes-validate
  become: true

- name: "Set check fact"
  ansible.builtin.set_fact:
    k3s_installed: true
  when:
    - k3s_main_node | default(false) | bool
    - k3s_check.rc == 0

- name: "Setup main k3s node"
  include_tasks: main-node.yml
  when:
    - k3s_main_node | default(false) | bool
    # - not k3s_installed

- name: "Setup worker k3s node"
  include_tasks: worker-node.yml
  when:
    - not k3s_main_node | default(false) | bool
    - not k3s_installed

- name: "Remove temp token file"
  ansible.builtin.file:
    path: "/tmp/node-token"
    state: absent
  delegate_to: localhost
  run_once: true
  when:
    - not k3s_main_node | default(false) | bool

- name: "Install helm"
  include_tasks: install-helm.yml
  when:
    - k3s_main_node | default(false) | bool
    - install_helm | default(true) | bool

- name: "Install cert-manager into the cluster"
  include_tasks: install-cert-manager.yml
  when:
    - k3s_main_node | default(false) | bool
    - install_certmgmr | default(true) | bool

- name: "Install metallb into the cluster"
  include_tasks: install-metallb.yml
  when:
    - k3s_main_node | default(false) | bool
    - install_metallb | default(false) | bool
