---
- name: "Install keepalived and required packages"
  apt:
    pkg:
      - raspberrypi-kernel-headers
      - keepalived
    state: present
  become: yes

- name: "Enable keepalived service"
  service:
    name: keepalived
    state: started
    enabled: yes
  become: yes

- name: "Template keepalived config"
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0640
  become: yes
  notify:
    - reload keepalived
