---
- name: "Install keepalived and required packages"
  ansible.builtin.apt:
    pkg:
      - raspberrypi-kernel-headers
      - keepalived
    state: present
  become: true

- name: "Enable keepalived service"
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true
  become: true

- name: "Template keepalived config"
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0640
  become: true
  notify:
    - reload keepalived
