---
- name: Test docker
  block:
    # Test docker works as expected locally
    - name: Create Test Container
      community.docker.docker_container:
        name: hello-world
        image: hello-world
        container_default_behavior: no_defaults
        state: present
      become: true

    - name: Get container info
      community.docker.docker_container_info:
        name: hello-world
      become: true
      register: status

    - name: Print Output of Test Container
      ansible.builtin.debug:
        msg: "{{ status }}"

    - name: Remove Test Container
      community.docker.docker_container:
        name: hello-world
        container_default_behavior: no_defaults
        state: absent
      become: true
