---
- name: Test docker
  block:
    # Test docker works as expected locally
    - name: Create Test Container
      docker_container:
        name: hello-world
        image: hello-world
        container_default_behavior: no_defaults
        state: present
      become: yes

    - name: Get container info
      docker_container_info:
        name: hello-world
      become: yes
      register: status

    - name: Print Output of Test Container
      debug:
        msg: "{{ status }}"

    - name: Remove Test Container
      docker_container:
        name: hello-world
        container_default_behavior: no_defaults
        state: absent
      become: yes
