name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install Ansible lint
        run: pip install ansible-core==2.13.3 ansible-lint==6.5.1

      - name: Install test requirements
        run: ansible-galaxy install -r test-requirements.yml

      - name: Run Ansible lint
        run: |
          export ANSIBLE_COLLECTIONS_PATH=/home/runner/.ansible/collections/ansible_collections
          ansible-lint -v
